spring:
  profiles:
    active: local
    include:
      - app
      - db
      - file
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  config:
    messages:
      basename: messages/bo/message
      encoding: UTF-8
  web:
    resources:
      add-mappings: false
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
---
# local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8079
  servlet:
    session:
      cookie:
        name: BO-JSESSIONID
bo:
  session:
    key-name: BO_SESSION_INFO
file:
  upload:
    path: C:/upload
    editor_path: C:/upload/editor
service:
  upload:
    path: /upload
api:
  url: http://localhost:21411
kicc:
  mid: T0021436
  transaction-url: https://testpgapi.easypay.co.kr/api/ep9/trades/webpay
  transaction-approval-url: https://testpgapi.easypay.co.kr/api/ep9/trades/approval
  transaction-callback-url: http://localhost:8079/payment/kicc/transaction/callback
---
# dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8079
  servlet:
    session:
      cookie:
        name: BO-JSESSIONID
bo:
  session:
    key-name: BO_SESSION_INFO
file:
  upload:
    path: /www/uploadFiles/aesk
    editor_path: /www/uploadFiles/aesk
service:
  upload:
    path: /upload
api:
  url: https://core-smanager.devsp.kr
kicc:
  mid: T0021436
  transaction-url: https://testpgapi.easypay.co.kr/api/ep9/trades/webpay
  transaction-approval-url: https://testpgapi.easypay.co.kr/api/ep9/trades/approval
  # FIXME :: 개발 배포 시 결제 콜백URL 변경
  transaction-callback-url: http://localhost:8079/payment/kicc/transaction/callback
---
# prod
spring:
  config:
    activate:
      on-profile: real
server:
  port: 79
  servlet:
    session:
      cookie:
        name: BO-JSESSIONID
bo:
  session:
    key-name: BO_SESSION_INFO
file:
  upload:
    path: /www/sites/aesk/upload
    editor_path: /www/sites/aesk/upload
service:
  upload:
    path: /upload
kicc:
  # FIXME :: 운영 배포 시 운영 MID 변경
  mid: T0021436
  transaction-url: https://pgapi.easypay.co.kr/api/ep9/trades/webpay
  transaction-approval-url: https://pgapi.easypay.co.kr/api/ep9/trades/approval
  # FIXME :: 운영 배포 시 결제 콜백URL 변경
  transaction-callback-url: http://localhost:8079/payment/kicc/transaction/callback
